version: "3.9"
name: todos

services:

  web:
    container_name: todos_server
    build: .
    networks:
      - api
    volumes:
      - .:/app
      # - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: todos_db
    image: postgres:latest
    ports:
      - "6543:5432"
    networks:
      - api
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
  # bundle:

networks:
  api:
