default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db
  # url: postgresql://0.0.0.0:6543
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

### env

development:
  <<: *default
  database: todo-api_dev

test:
  <<: *default
  database: todo-api_test

production:
  <<: *default
  database: todo-api_prod
