default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # host: db
  url: postgresql://0.0.0.0:5432
  username: <%= Rails.application.credentials.dig(:pg, :user) %>
  password: <%= Rails.application.credentials.dig(:pg, :password) %>

### env

development:
  <<: *default
  database: todo-api_dev

test:
  <<: *default
  database: todo-api_test

production:
  <<: *default
  database: todo-api_prod
