default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

### env

development:
  <<: *default
  host: localhost
  port: 5432
  username: <%= Rails.application.credentials.dig(:pg, :user) %>
  password: <%= Rails.application.credentials.dig(:pg, :password) %>
  database: todo-api_dev

test:
  <<: *default
  host: localhost
  port: 5432
  username: <%= Rails.application.credentials.dig(:pg, :user) %>
  password: <%= Rails.application.credentials.dig(:pg, :password) %>
  database: todo-api_test

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:elephant, :host) %>
  port: <%= Rails.application.credentials.dig(:elephant, :port) %>
  username: <%= Rails.application.credentials.dig(:elephant, :user) %>
  password: <%= Rails.application.credentials.dig(:elephant, :password) %>
  database: <%= Rails.application.credentials.dig(:elephant, :dbname) %>
